name: ci
concurrency:
  group: production
  cancel-in-progress: true

on:
  push:
    branches:
      - main

jobs:
  docker-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latest,ghcr.io/${{ github.repository }}:${{ github.sha }}
          build-args: |
            NPM_CONFIG_USERCONFIG=.npmrc.ci
            NPM_TOKEN=${{ secrets.GHCR_TOKEN }}

      - name: Deploy to cluster
        uses: danielr1996/kubectl-action@1.0.0
        if: ${{ !startsWith(github.event.head_commit.message, '[no deploy]') }}
        with:
          kubeconfig: ${{ secrets.KUBECONFIG }}
          args: set image --record deployment/gateway -n puff app=ghcr.io/${{ github.repository }}:${{ github.sha }}

      - name: Verify deployment
        uses: danielr1996/kubectl-action@1.0.0
        if: ${{ !startsWith(github.event.head_commit.message, '[no deploy]') }}
        with:
          kubeconfig: ${{ secrets.KUBECONFIG }}
          args: rollout status deployment/gateway -n puff
